name: magnet
channels:
  - pytorch
  - fastai
  - conda-forge
  - defaults
  - HCC
dependencies:
- matplotlib
- pandas=1.1.1
- numpy=1.17.3
- scipy=1.5.4
- lightgbm=2.3.2
- requests
- feather-format=0.4.0
- click=7.0
- joblib=0.13.2
- tqdm=4.43.0
- mlflow=1.3.0
- scikit-learn=0.23.2
- pyyaml
- pytorch=1.0.0