name: magnet
channels:
  - pytorch
  - fastai
  - conda-forge
  - defaults
  - HCC
dependencies:
- matplotlib
- pandas=1.1.2
- numpy=1.18.5
- scipy=1.5.2
- lightgbm=3.0.0
- feather-format
- click
- joblib
- tqdm
- mlflow
- scikit-learn=0.23.2
- pyyaml
- pytorch=1.7.0